#!/bin/bash

# Used on 'Repl.it' (online demonstration).

chr() {
  [ "$1" -lt 256 ] || return 1
  printf "\\$(printf '%03o' "$1")"
}

ord() {
  LC_CTYPE=C printf '%d' "'$1"
}

DEMOS=(Excel-1 Excel-3)

export DEMOS_AMOUNT=${#DEMOS[@]}

CONT=true

while [ "$CONT" == "true" ]
do
  echo

  for i in "${!DEMOS[@]}"
  do
    printf "%s: %s\n" "$(chr $((97 + $i )))" "${DEMOS[$i]}"  
  done

  echo -n -e "\nChoose example to launch ('a'…'$(chr $((96 + $DEMOS_AMOUNT)))'): "

  read DEMO

  export FILE=${DEMOS[$(($(ord $DEMO) - 97))]}

  [ -f $FILE/main.py ] && CONT=false && python $FILE/main.py && echo "IF AN ERROR MESSAGE IS DISPLAYED INSTEAD OF THE QR CODE\NPLEASE CLICK THE RELOAD BUTTON TOP LEFT OF THE CORRESPONDING FRAME!" 
done
